### ISSUE TITLE
error when uploading artifacts to custom S3 bucket

### ISSUE THREAD

**Issue by AdamNowotny** [buildkite/elastic-ci-stack-for-aws#347]
Trying to setup S3 bucket for artifacts as described in https://buildkite.com/docs/agent/cli-artifact#using-your-own-s3-bucket
So far no luck, any ideas what am I doing wrong?
I'm using the 3.0 beta agent, created the bucket, added "s3:*" permissions using a policy set on the IAM role that BuildKite stack created.
Next I upload ```env``` hook to the secrets bucket:
```
export BUILDKITE_ARTIFACT_UPLOAD_DESTINATION="s3://buildkite-artifactsbucket-xxxxxx/$BUILDKITE_JOB_ID"
export BUILDKITE_S3_DEFAULT_REGION="ap-southeast-2"
```
The build runs fine, but fails when trying to upload artifacts, same happens when running ```buildkite-agent artifact upload``` from command line.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c96c3]

goroutine 1 [running]:
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).GetMetadata(0x0, 0xd83862, 0x19, 0x918a0, 0x12dee40, 0xcb0ba0, 0xcb0ba0)
	/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:26 +0x153
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.requestCredList(0x0, 0x1, 0x12dfae0, 0x7f0af5374290, 0x10000c4200001a0, 0xc4201b7cc8)
	/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:133 +0x58
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.(*EC2RoleProvider).Retrieve(0xc4201733e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7f0af5374290, ...)
	/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:89 +0x65
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/credentials.(*ChainProvider).Retrieve(0xc420173440, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xcbcc60, ...)
	/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/credentials/chain_provider.go:77 +0xc9
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).Get(0xc420053920, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/credentials/credentials.go:208 +0x13a
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/signer/v4.Signer.signWithBody(0xc420053920, 0x0, 0x127b300, 0xc42000c1b0, 0x10100, 0xda4da8, 0x0, 0xc4200ad400, 0x127f900, 0xc420187360, ...)
	/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go:338 +0x259
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/signer/v4.signSDKRequestWithCurrTime(0xc4201da400, 0xda4da8, 0x0, 0x0, 0x0)
	/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go:472 +0x2f4
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/signer/v4.SignSDKRequest(0xc4201da400)
	/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go:416 +0x52
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc4201da570, 0xc4201da400)
	/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/request/handlers.go:164 +0x87
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).Sign(0xc4201da400, 0xda38d0, 0xc4201da400)
	/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:337 +0xb0
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc4201da400, 0x0, 0x0)
	/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:474 +0x13d
github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjects(0xc42000c1c0, 0xc42001fc00, 0x0, 0x0, 0x0)
	/go/src/github.com/buildkite/agent/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:3887 +0x4d
github.com/buildkite/agent/agent.newS3Client(0x7ffc2e1044b4, 0x19, 0x19, 0xc420173301, 0xc420167ff0)
	/go/src/github.com/buildkite/agent/agent/s3.go:108 +0x55c
github.com/buildkite/agent/agent.(*S3Uploader).Setup(0xc420186d00, 0x7ffc2e1044af, 0x1f, 0x0, 0xd6e301, 0x4)
	/go/src/github.com/buildkite/agent/agent/s3_uploader.go:35 +0x6e
github.com/buildkite/agent/agent.(*ArtifactUploader).upload(0xc42001fb80, 0xc42000c1a8, 0x1, 0x1, 0x2, 0x0)
	/go/src/github.com/buildkite/agent/agent/artifact_uploader.go:152 +0x13f
github.com/buildkite/agent/agent.(*ArtifactUploader).Upload(0xc42001fb80, 0x1e, 0x7ffc2e1044ef)
	/go/src/github.com/buildkite/agent/agent/artifact_uploader.go:47 +0x212
github.com/buildkite/agent/clicommand.glob..func5(0xc420194a00)
	/go/src/github.com/buildkite/agent/clicommand/artifact_upload.go:91 +0x297
github.com/buildkite/agent/vendor/github.com/urfave/cli.HandleAction(0xbbf0a0, 0xda37b0, 0xc420194a00, 0xc420053600, 0x0)
	/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/app.go:487 +0x7c
github.com/buildkite/agent/vendor/github.com/urfave/cli.Command.Run(0xd70cfa, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd8e5ce, 0x23, 0x0, ...)
	/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/command.go:207 +0xb72
github.com/buildkite/agent/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc420180340, 0xc420194780, 0x0, 0x0)
	/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/app.go:374 +0xacc
github.com/buildkite/agent/vendor/github.com/urfave/cli.Command.startApp(0xd72858, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd9537f, 0x2d, 0x0, ...)
	/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/command.go:293 +0x8a3
github.com/buildkite/agent/vendor/github.com/urfave/cli.Command.Run(0xd72858, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd9537f, 0x2d, 0x0, ...)
	/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/command.go:93 +0x14c7
github.com/buildkite/agent/vendor/github.com/urfave/cli.(*App).Run(0xc4201801a0, 0xc42000e090, 0x9, 0x9, 0x0, 0x0)
	/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
	/go/src/github.com/buildkite/agent/main.go:102 +0x565
```

**Comment by lox** [comment]
Sorry about this! Sounds like an agent bug. I will investigate.

**Comment by AdamNowotny** [comment]
Tried that again and it seems to not be happening anymore with latest 3.x version. The only annoyance is that the environment variables are ignored when using agent upload command instead of artifact_upload step property (https://github.com/buildkite/agent/issues/292).
